<a href="https://colab.research.google.com/github/ECV21/Course-Data-Analysis-with-Python-FreeCodeCamp/blob/main/NumPy_FreeCodeCamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

Efficient numeric computation with C primitives
Efficient collections with vectorized operations
An integrated and natural Linear Algebra API
A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.
Let's develop on efficiency. In Python, everything is an object, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

In [27]:
#import libraries


import sys
import numpy as np

#Basic Numpy arrays

In [6]:
#Array
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [7]:
#create array A
a = np.array([1, 2, 3, 4])

In [10]:
a

array([1, 2, 3, 4])

In [8]:
b = np.array([0, .5, 1, 1.5, 2])

In [11]:
#give me the first and the second element
a[0], a[1]

(1, 2)

In [12]:
#give me elements more than first element
a[0:]

array([1, 2, 3, 4])

In [14]:
#give me elements between 2 an 3
a[1:3]

array([2, 3])

In [15]:
a[1:-1]

array([2, 3])

In [17]:
a

array([1, 2, 3, 4])

In [16]:
#daleme elementos cons saltos de 2 en dos
a[::2]

array([1, 3])

In [18]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [20]:
#to extract three elements out of it:

#firs position, third position and last position
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [21]:
#multi index
b[[0, 2, -1]]

array([0., 1., 2.])

#Array types

In [22]:
a

array([1, 2, 3, 4])

In [23]:
a.dtype

dtype('int64')

In [24]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [25]:
b.dtype

dtype('float64')

In [30]:
#definir el tipo de array: float
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [29]:
#definir el tipo de array como int:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [34]:
#string array
c = np.array(['a', 'b', 'c'])

In [33]:
c.dtype

dtype('<U1')

In [35]:
d = np.array([{'a': 1}, sys])

In [36]:
d.dtype

dtype('O')

#Dimensions and shapes

In [37]:
#two dimensional array: we hae two rows and three columns

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [39]:
A.shape #2 rows and 3 columns

(2, 3)

In [41]:
A.ndim #dimensinal 2

2

In [43]:
#total elements we have

A.size

6

In [44]:
#three dimensional object=three dimensional array, which is basically a cube,
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [45]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [46]:
B.shape

(2, 2, 3)

In [47]:
B.ndim

3

In [48]:
#SIZE is a total count of elements: 12
B.size

12

In [49]:
#error in dimensional of array:


C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [50]:
C.dtype


NameError: name 'C' is not defined

In [51]:
C.shape

NameError: name 'C' is not defined

In [52]:
C.size

NameError: name 'C' is not defined

In [53]:
type(C[0])

NameError: name 'C' is not defined

#indexing and slicing of matrices

In [54]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [55]:
#give me the second row
A[1]

array([4, 5, 6])

In [57]:
#give me the element in the second row and first column
A[1][0]

4

In [60]:
 #A[d1, d2, d3, d4]

In [61]:
#multi select: second row and first column
A[1, 0]

4

In [63]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
#You say from ZERO up to two(the two is not included) rows
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
#select all elements only want to select the elements up to two

A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [67]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [68]:
A[:2, 2:]

array([[3],
       [6]])

In [69]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
#reemplazar elementos de fila 1, index 1
A[1] = np.array([10, 10, 10])

In [71]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [72]:
#reemplazar elementos de fila 2, index 2, con num 99
A[2] = 99

In [73]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#summay statistics

In [74]:
a = np.array([1, 2, 3, 4])

In [76]:
a

array([1, 2, 3, 4])

In [78]:
#sum method
a.sum()

10

In [79]:
a.mean()

2.5

In [80]:
a.std()

1.118033988749895

In [81]:
a.var()

1.25

In [82]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [83]:
A.sum()

45

In [84]:
A.mean()

5.0

In [86]:
A.std()

2.581988897471611

In [87]:
#realizar operacion por columnas
A.sum(axis=0)

array([12, 15, 18])

In [89]:
#realizar suma por ROWs
A.sum(axis=1)

array([ 6, 15, 24])

In [90]:
A.mean(axis=0)

array([4., 5., 6.])

In [91]:
A.mean(axis=1)

array([2., 5., 8.])

In [92]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [93]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

#Broadcasting and vectorized operations

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
a + 10

In [ ]:
a * 10

In [ ]:
a

In [ ]:
a += 100

In [ ]:
a

In [ ]:
l = [0, 1, 2, 3]

In [ ]:
[i * 10 for i in l]

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
b = np.array([10, 10, 10, 10])

In [ ]:
b

In [ ]:
a + b

In [ ]:
a * b

#Boolean arrays

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
a[0], a[-1]

In [ ]:
a[[0, -1]]

In [ ]:
a[[True, False, False, True]]

In [ ]:
a

In [ ]:
a >= 2

In [ ]:
a[a >= 2]

In [ ]:
a.mean()

In [ ]:
a[a > a.mean()]

In [ ]:
a[~(a > a.mean())]

In [ ]:
a[(a == 0) | (a == 1)]

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

In [ ]:
A > 30

In [ ]:
A[A > 30]

#Linear Algebra

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B)

In [ ]:
A @ B

In [ ]:
B.T

In [ ]:
A

In [ ]:
B.T @ A

#Size of objects in memory

In [ ]:
# int, floats

In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

In [ ]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

In [ ]:
np.dtype(float).itemsize

#List are even larger

In [ ]:
# A one-element list
sys.getsizeof([1])

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

#And performance is also important

In [ ]:
l = list(range(100000))

In [ ]:
a = np.arange(100000)

In [ ]:
%time np.sum(a ** 2)

In [ ]:
%time sum([x ** 2 for x in l])

#Useful Numpy functions

In [ ]:
#random

In [ ]:
np.random.random(size=2)

In [ ]:
np.random.normal(size=2)

In [ ]:
np.random.rand(2, 4)

In [ ]:
#Arange

In [ ]:
np.arange(10)

In [ ]:
np.arange(5, 10)

In [ ]:
np.arange(0, 1, .1)

In [ ]:
#reshape

In [ ]:
np.arange(10).reshape(2, 5)

In [ ]:
np.arange(10).reshape(5, 2)

In [ ]:
#linspace

In [ ]:
np.linspace(0, 1, 5)

In [ ]:
np.linspace(0, 1, 20)

In [ ]:
np.linspace(0, 1, 20, False)

In [ ]:
#Zeros, ones, empty

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3, 3))

In [ ]:
np.zeros((3, 3), dtype=np.int)

In [ ]:
np.ones(5)

In [ ]:
np.ones((3, 3))

In [ ]:
np.empty(5)

In [ ]:
np.empty((2, 2))

In [ ]:
#identity and eye

In [ ]:

np.identity(3)

In [ ]:
np.eye(3, 3)

In [ ]:
np.eye(8, 4)

In [ ]:
np.eye(8, 4, k=1)

In [ ]:
np.eye(8, 4, k=-3)

In [ ]:
"Hello World"[6]