<a href="https://colab.research.google.com/github/ECV21/Course-Data-Analysis-with-Python-FreeCodeCamp/blob/main/NumPy_FreeCodeCamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

Efficient numeric computation with C primitives
Efficient collections with vectorized operations
An integrated and natural Linear Algebra API
A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.
Let's develop on efficiency. In Python, everything is an object, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

In [27]:
#import libraries


import sys
import numpy as np

#Basic Numpy arrays

In [6]:
#Array
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [7]:
#create array A
a = np.array([1, 2, 3, 4])

In [10]:
a

array([1, 2, 3, 4])

In [8]:
b = np.array([0, .5, 1, 1.5, 2])

In [11]:
#give me the first and the second element
a[0], a[1]

(1, 2)

In [12]:
#give me elements more than first element
a[0:]

array([1, 2, 3, 4])

In [14]:
#give me elements between 2 an 3
a[1:3]

array([2, 3])

In [15]:
a[1:-1]

array([2, 3])

In [17]:
a

array([1, 2, 3, 4])

In [16]:
#daleme elementos cons saltos de 2 en dos
a[::2]

array([1, 3])

In [18]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [20]:
#to extract three elements out of it:

#firs position, third position and last position
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [21]:
#multi index
b[[0, 2, -1]]

array([0., 1., 2.])

#Array types

In [22]:
a

array([1, 2, 3, 4])

In [23]:
a.dtype

dtype('int64')

In [24]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [25]:
b.dtype

dtype('float64')

In [30]:
#definir el tipo de array: float
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [29]:
#definir el tipo de array como int:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [34]:
#string array
c = np.array(['a', 'b', 'c'])

In [33]:
c.dtype

dtype('<U1')

In [35]:
d = np.array([{'a': 1}, sys])

In [36]:
d.dtype

dtype('O')

#Dimensions and shapes

In [37]:
#two dimensional array: we hae two rows and three columns

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [39]:
A.shape #2 rows and 3 columns

(2, 3)

In [41]:
A.ndim #dimensinal 2

2

In [43]:
#total elements we have

A.size

6

In [44]:
#three dimensional object=three dimensional array, which is basically a cube,
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [45]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [46]:
B.shape

(2, 2, 3)

In [47]:
B.ndim

3

In [48]:
#SIZE is a total count of elements: 12
B.size

12

In [49]:
#error in dimensional of array:


C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [50]:
C.dtype


NameError: name 'C' is not defined

In [51]:
C.shape

NameError: name 'C' is not defined

In [52]:
C.size

NameError: name 'C' is not defined

In [53]:
type(C[0])

NameError: name 'C' is not defined

#indexing and slicing of matrices

In [54]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [55]:
#give me the second row
A[1]

array([4, 5, 6])

In [57]:
#give me the element in the second row and first column
A[1][0]

4

In [60]:
 #A[d1, d2, d3, d4]

In [61]:
#multi select: second row and first column
A[1, 0]

4

In [63]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
#You say from ZERO up to two(the two is not included) rows
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
#select all elements only want to select the elements up to two

A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [67]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [68]:
A[:2, 2:]

array([[3],
       [6]])

In [69]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
#reemplazar elementos de fila 1, index 1
A[1] = np.array([10, 10, 10])

In [71]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [72]:
#reemplazar elementos de fila 2, index 2, con num 99
A[2] = 99

In [73]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#summay statistics

In [74]:
a = np.array([1, 2, 3, 4])

In [76]:
a

array([1, 2, 3, 4])

In [78]:
#sum method
a.sum()

10

In [79]:
a.mean()

2.5

In [80]:
a.std()

1.118033988749895

In [81]:
a.var()

1.25

In [82]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [83]:
A.sum()

45

In [84]:
A.mean()

5.0

In [86]:
A.std()

2.581988897471611

In [87]:
#realizar operacion por columnas
A.sum(axis=0)

array([12, 15, 18])

In [89]:
#realizar suma por ROWs
A.sum(axis=1)

array([ 6, 15, 24])

In [90]:
A.mean(axis=0)

array([4., 5., 6.])

In [91]:
A.mean(axis=1)

array([2., 5., 8.])

In [92]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [93]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

#Broadcasting and vectorized operations

In [94]:
a = np.arange(4)

In [95]:
a

array([0, 1, 2, 3])

In [97]:
#we're going to sum the entire array plus 10
a + 10

#That each one the elements within the array will be applied the separation
#Vectorization: the operation is applied to EACH one of the elements

array([10, 11, 12, 13])

In [98]:
a * 10

array([ 0, 10, 20, 30])

In [99]:
a

array([0, 1, 2, 3])

In [100]:
a += 100

In [101]:
a

array([100, 101, 102, 103])

In [102]:
l = [0, 1, 2, 3]

In [103]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [104]:
a = np.arange(4)

In [105]:
a

array([0, 1, 2, 3])

In [106]:
b = np.array([10, 10, 10, 10])

In [107]:
b

array([10, 10, 10, 10])

In [108]:
a + b

array([10, 11, 12, 13])

In [109]:
a * b

array([ 0, 10, 20, 30])

#Boolean arrays

In [117]:
a = np.arange(4)

In [119]:
a

array([0, 1, 2, 3])

In [112]:
a[0], a[-1]

(0, 3)

In [114]:
a[[0, -1]]

array([0, 4])

In [118]:
a[[True, False, False, True]]

array([0, 3])

In [120]:
a

array([0, 1, 2, 3])

In [121]:
#greater than or equals to the number two
a >= 2

array([False, False,  True,  True])

In [122]:
#muestra los elementos que cumple la condicion
a[a >= 2]

array([2, 3])

In [123]:
a.mean()

1.5

In [124]:
a[a > a.mean()]

array([2, 3])

In [125]:
a[~(a > a.mean())]

array([0, 1])

In [126]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [127]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [128]:
A = np.random.randint(100, size=(3, 3))

In [129]:
A

array([[23, 35, 91],
       [11, 75, 26],
       [52, 54, 52]])

In [130]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([23, 91, 75, 52, 52])

In [131]:
A > 30

array([[False,  True,  True],
       [False,  True, False],
       [ True,  True,  True]])

In [132]:
A[A > 30]

array([35, 91, 75, 52, 54, 52])

#Linear Algebra

In [133]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [134]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [135]:
#realizar el producto punto (o producto escalar) entre A y B
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [140]:
#multiplicación de matrices
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [137]:
#btener la transpuesta de matriz B o un array
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [138]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
#ealiza una multiplicación de matrices entre la transpuesta de la matriz B y la matriz A
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

#Size of objects in memory

In [ ]:
# int, floats

In [141]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [142]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [143]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [144]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [145]:
np.dtype(float).itemsize

8

#List are even larger

In [147]:
# A one-element list
sys.getsizeof([1])

64

In [148]:
# An array of one element in numpy
np.array([1]).nbytes

8

#And performance is also important

In [149]:
l = list(range(100000))

In [150]:
a = np.arange(100000)

In [151]:
%time np.sum(a ** 2)

CPU times: user 2.01 ms, sys: 0 ns, total: 2.01 ms
Wall time: 2.03 ms


333328333350000

In [152]:
%time sum([x ** 2 for x in l])

CPU times: user 47.8 ms, sys: 3.52 ms, total: 51.3 ms
Wall time: 61.4 ms


333328333350000

#Useful Numpy functions

In [ ]:
#random

In [153]:
np.random.random(size=2)

array([0.26996317, 0.03831196])

In [154]:
np.random.normal(size=2)

array([1.38606936, 0.99115605])

In [155]:
np.random.rand(2, 4)

array([[0.23649602, 0.0712515 , 0.13697256, 0.72408577],
       [0.74352126, 0.95009762, 0.19600116, 0.73263831]])

In [ ]:
#Arange

In [156]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [158]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
#reshape

In [159]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [160]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
#linspace

In [161]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [162]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [163]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [164]:
#Zeros, ones, empty

In [165]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [166]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [167]:
np.zeros((3, 3), dtype=np.int)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [168]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [169]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [170]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [171]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [ ]:
#identity and eye

In [172]:

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [173]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [174]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [175]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [176]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [177]:
"Hello World"[6]

'W'